NEW: `signer list` column `used` with references to this (e.g., as a …
tonlabs/tondev pull request #40
Opened 2021-06-25 09:45 UTC by melsomino

…signer for network giver).

NEW: `network list` column `giver` add information about giver contract and signer.
NEW: printed tables now supports multiline cell values.
FIX: "Error: Signer not found:" in case when the default signer has upper letters in name.
FIX: Giver didn't use default signer. From now the giver uses default signer
  when the user calls the `network giver` command without `--signer` option.

2021-06-29 14:16 UTC, elasticLove1 requested changes
Need to update the changelog with topup command fix

2021-06-30 10:37 UTC, Artem-Zhdanov approved these changes

2021-07-02 11:38 UTC, elasticLove1 approved these changes

2021-07-02 12:22 UTC, d3p approved these changes

2021-07-02 12:22 UTC, merged