ast-json
tonlabs/tondev pull request #65
Opened 2021-10-13 07:36 UTC by freeton20

2021-11-01 20:46 UTC, elasticLove1 approved these changes

2021-11-02 06:50 UTC, melsomino requested changes
see comments

2021-11-02 06:50 UTC, melsomino commented on README.md
> +tondev sol ast-compact-json Contract.sol
I think it is better to name command as `ast` and add option `-f, --format <json | compact-json>`

2021-11-04 11:16 UTC, elasticLove1 commented
@freeton20 How is it going with the requested changes?

2021-11-05 15:11 UTC, closed without merging

2021-11-05 18:22 UTC, freeton20 commented
> @freeton20 How is it going with the requested changes?
Sorry for delay and new PR (playing with git:-)

https://github.com/tonlabs/tondev/pull/68