Add old solc and linker to compile SafeMultisigWallet
tonlabs/tondev pull request #69
Opened 2021-11-11 18:06 UTC by Artem-Zhdanov

See CHANGELOG

Steps to test:
1. Check that old functionality still works
```
$ npm i
$ tsc
$ rm -rf ~/.tondev/solidity/
$ node cli.js sol create
$ node cli.js sol compile Contract.sol 
Solidity contract Contract.sol created.

$ node cli.js sol version
Component  Version  Available
---------  -------  ---------------------------------------------------------------------------------------------
compiler   0.51.0   0.51.0, 0.50.0, 0.49.0, 0.48.0, 0.47.0, 0.46.0, 0.45.0, 0.44.0, 0.43.0, 0.42.0, ...
linker     0.13.88  0.13.88, 0.13.87, 0.13.86, 0.13.85, 0.13.84, 0.13.83, 0.13.82, 0.13.73, 0.13.72, 0.13.71, ...
stdlib     0.51.0   0.51.0, 0.50.0, 0.49.0, 0.48.0, 0.47.0, 0.46.0, 0.45.0, 0.44.0, 0.43.0, 0.42.0, ...
[tiger@localhost tondev]$ 
```
2. Check that new functionality works
```
$ curl https://raw.githubusercontent.com/tonlabs/ton-labs-contracts/master/solidity/safemultisig/SafeMultisigWallet.sol -o SafeMultisigWallet.sol

$ node cli.js sol set -c 0.21.0
$ node cli.js  sol set -s 0.21.0
$ node cli.js sol set -l 0.1.21
$ node cli.js sol compile  SafeMultisigWallet.sol 
You use an obsolete version of the compiler.
The output files are saved in the current directory

$ ls -l SafeMultisigWallet.tvc 
-rw-rw-r--. 1 4430 Nov 11 23:03 SafeMultisigWallet.tvc
```
OK. now we can compile SafeMultisigWallet

2021-11-11 18:14 UTC, melsomino requested changes
see comments

2021-11-11 18:14 UTC, melsomino commented on src/controllers/solidity/index.ts
> +        if (isDepricatedVersion) {
* Deprecated

2021-11-11 18:14 UTC, melsomino commented on src/core/component.ts
> +            const isDepricatedVersion = !!(_downloadedVersion.match(/^0.21.0$|^0.1.21$/))
* Deprecated

2021-11-11 18:14 UTC, melsomino commented on src/core/component.ts
> +            return isDepricatedVersion
deprecated

2021-11-11 18:19 UTC, Artem-Zhdanov commented on src/core/component.ts
> +            return isDepricatedVersion
fixed

2021-11-11 18:19 UTC, Artem-Zhdanov commented on src/controllers/solidity/index.ts
> +        if (isDepricatedVersion) {
fixed

2021-11-11 19:01 UTC, elasticLove1 approved these changes

2021-11-12 07:15 UTC, melsomino approved these changes

2021-11-12 08:20 UTC, merged